
server:
  port: 9002
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
         enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug
