spring:
  application:
    name: spring-cloud-provider
#链路追踪
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
server:
   port: 9005

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/


