spring:
  application:
    name: spring-cloud-customer
  #链路追踪
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

server:
   port: 9003
#   servlet:
#    context-path: /SPRING-CLOUD-CUSTOMER
#server.context-path=/项目名  server.servlet.context-path
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/


feign:
  hystrix:
    enabled: true


