
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
server:
  port: 9411
spring:
  application:
    name: zipkin-server

management:
   metrics:
     web:
       server:
       #±‹√‚∑√Œ zipkin“≥√Ê±®java.lang.IllegalArgumentException
         auto-time-requests: false